

[font]
size = 14
normal = {family = "Hack Nerd Font", style="Regular"}
italic = {family = "Hack Nerd Font", style="Italic"}
bold = {family = "Hack Nerd Font", style="Bold"}
bold_italic = {family = "Hack Nerd Font", style = "Bold Italic"}


[window]
padding = {x=5, y=4}
decorations = "Buttonless"

